### PR TITLE
added some editor tmThemes and settings

### PR DESCRIPTION
**Pull request by thecodymetalist**
Converted collection of tmThemes for making them usable with app and added one common app dark theme for using dark editor themes with it.

Themes converted from his repo:
https://github.com/filmgirl/TextMate-Themes

> check at least one

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [x] Other, new UI options

### Validations

- [x] Follow our [CONTRIBUTING](https://github.com/massCodeIO/massCode/blob/master/CONTRIBUTING.md) guide

### CODE REVIEW

**Comment by thecodymetalist** [comment]
i couldnt make a build without any error. So please make a new release to people can test themes. Some of them may need removing or editing. @antonreshetov

**Comment by antonreshetov** [comment]
_> So please make a new release so people can test themes._

You need a merge, build and release so that users can test it. But this process is not for a test, but for a finished release. There are no beta stages in the project at the current time.

_> Some of them may need removing or editing._

I don't understand why something should be edited or removed. Why include it in PR and who should do it.

You've done a great job, but you should have started by asking if new themes are needed, if there are any plans to add them at all. As of today, I have no plans to do so.

**Comment by thecodymetalist** [comment]
> _> So please make a new release so people can test themes._
> 
> You need a merge, build and release so that users can test it. But this process is not for a test, but for a finished release. There are no beta stages in the project at the current time.
> 
> _> Some of them may need removing or editing._
> 
> I don't understand why something should be edited or removed. Why include it in PR and who should do it.
> 
> You've done a great job, but you should have started by asking if new themes are needed, if there are any plans to add them at all. As of today, I have no plans to do so.

If app's package.json config was not conflicted and could be builded succesfully, i could test it and no need a PR from you. Everybody could use it for self without a release. 

And you said you have no plans for adding new themes, so what is this comment of you?

https://github.com/massCodeIO/massCode/discussions/63#discussioncomment-2677409

**Comment by antonreshetov** [comment]
> If app's package.json config was not conflicted and could be builded succesfully, i could test it and would no need a PR from you. Everybody could use it for self without a release.

I don't know what conflict you are talking about and what the configuration of package.json has to do with it. The fact that there are constant releases suggests that the application is working in the dev build and builds in prod without errors.

> https://github.com/massCodeIO/massCode/discussions/63#discussioncomment-2677409

My comment was two years ago. Time changes, plans too. There is also this [point](https://github.com/massCodeIO/massCode/blob/master/CONTRIBUTING.md#discuss-first).

Since this is OSS, you can make your own version however you want.

P.S. Don't take it personally.

**Pull request closed without merging**
