### PR TITLE
feat: add Simplified Chinese for i18n

### PR DESCRIPTION
**Pull request by sangyuxiaowu**
I just found out that this project has not been used yet. It took some time to pull the code, and the translation process also understands the functions. The submission is slow, you can make a reference to complement each other. It's early morning here, so I'm going to bed first.

### CODE REVIEW

**Comment by antonreshetov** [comment]
@sangyuxiaowu Sorry but #154 was the first.

**Comment by AuroraTea** [comment]
@antonreshetov  From the wording he should have known, but he was still willing to translate a version as a reference to compare to improve the Chinese version. This is an act of kindness done by kind people for his approbatory project.

**Comment by sangyuxiaowu** [comment]
> @antonreshetov From the wording he should have known, but he was still willing to translate a version as a reference to compare to improve the Chinese version. This is an act of kindness done by kind people for his approbatory project.

Yes, everyone is willing to help massCode do better.

**Comment by antonreshetov** [comment]
@sangyuxiaowu Maybe it makes sense to close this PR?

**Comment by sangyuxiaowu** [comment]
> 

Okay, submitting this PR just shows that everyone is willing to help you.

**Pull request closed without merging**
