### PR TITLE
feat: add DigitalOcean, Moodle and Oracle icons

### PR DESCRIPTION
**Pull request by adpe**
### What kind of change does this PR introduce?

Change which was discussed in https://github.com/massCodeIO/massCode/discussions/385

> check at least one

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Other, please describe:

### Validations

- [x] Follow our [CONTRIBUTING](https://github.com/massCodeIO/massCode/blob/master/CONTRIBUTING.md) guide

### CODE REVIEW

**Comment by antonreshetov** [comment]
The files look unoptimized. Use svgo or other svg optimization utilities. Better yet, find a good collection of icons that follow svg best practices.

**Comment by antonreshetov** [comment]
Big collection of icons https://icones.js.org/

**Comment by Faq** [comment]
optimize svg https://jakearchibald.github.io/svgomg/

**Comment by antonreshetov** [comment]
The icons should also be fitted into a square and have a margin. You can take any icon from https://github.com/massCodeIO/massCode/tree/master/src/renderer/assets/svg/icons as an example.

**Comment by adpe** [comment]
Got it! Thank you very much. Updated and added also a new one.

**Review by antonreshetov — APPROVED** [review]

**Pull request merged**
