### PR TITLE
Update Portuguese translation

### PR DESCRIPTION
**Pull request by andercard0**
Update file to latest.

### CODE REVIEW

**Comment by antonreshetov** [comment]
Something is not right here. Your PR has only part of the data. This PR https://github.com/massCodeIO/massCode/pull/203 according to GitHub you supposedly merged, but it's not possible.

**Comment by andercard0** [comment]
> Something is not right here. Your PR has only part of the data. This PR #203 according to GitHub you supposedly merged, but it's not possible.

I did ask you before in the previous PR what should i have to do with it, you didn't reply but you said that it has been merged. so, I updated my branch to match the current --as you suggested. because thought it has been merged. So, what do you want me to do now ? Please, be more especific and clear, this project is a bit more different from the others I'm 🤔 just want to avoid conflicts and confusion to the project!

**Comment by antonreshetov** [comment]
First of all, this is not a live chat, to respond promptly. 

Secondly, I did not say that I merged your PR.  I said that I merged my PR #215 and that there are new locales which appeared later than your PR and that it would be good if you could pull the master and complement your PR. It turns out you have not even tested what you give to the PR. 

Today also was PR #214 on localization and I wrote the same thing. It seems that there were no misunderstandings.

**Comment by antonreshetov** [comment]
Then a strange thing happened, they say you merged your PR into the master, at least so displayed GitHub. But it is not possible. 

If you wanted to update your branch to origin/master, you obviously did something wrong.

**Comment by andercard0** [comment]
> Then a strange thing happened, they say you merged your PR into the master, at least so displayed GitHub. But it is not possible.
> 
> If you wanted to update your branch to origin/master, you obviously did something wrong.

Perhpas, I recently started to use Github desktop application and honestly could be that where my issues started.. 
What would you recommend to do in this case to fix this problems?

**Comment by antonreshetov** [comment]
In order for me to merge this PR you need to add the missing locales that were in the previous PR #203 that you closed. Also a big request this is not a training field, I do not have time to understand and teach. Please read about Git and other general agreements on using GitHub.

**Pull request closed without merging**
