### PR TITLE
Added New Translation

### PR DESCRIPTION
**Pull request by andercard0**
Localization and some word tweaks (adaptation) for my language, Brazilian Portugue hope it be usefull.
I hope I did not missed anything else this time :) 

Note:
There is a typo in the original language 'File preferences.json' line: "showInvisibles": "Snow Invisibles" should be Show not Snow.

### CODE REVIEW

**Comment by antonreshetov** [comment]
@andercard0 Again, please read [how](https://github.com/massCodeIO/massCode/tree/master/src/main/services/i18n/locales), and test what you would have done before PR. Have some respect. 

Based on the name of your commit, which does not respond to convention, you did not install the project or run it.

**Comment by andercard0** [comment]
> @andercard0 Again, please read [how](https://github.com/massCodeIO/massCode/tree/master/src/main/services/i18n/locales), and test what you would have done before PR. Have some respect.
> 
> Based on the name of your commit, which does not respond to convention, you did not install the project or run it.

Hi, I'm sorry but what? where did i unrespected you ? Only mentioned the typo in the original language if this is what you mean.
Also, no haven't test it here did followed what it's said in the docs changing the correct line to add my language, folder and the other files translated. 

Could you please point me out what is missing ?

**Comment by antonreshetov** [comment]
@andercard0 I don't mean respect for myself, but respect for the repository and the work.  You didn't install dependencies, you didn't test your code, yet you sent a PR. 

Detail:
- commits must comply with the agreement - https://github.com/massCodeIO/massCode/blob/master/commitlint.config.js
- you didn't add a new option to the language selector, how to do that is described here - https://github.com/massCodeIO/massCode/blob/master/src/main/services/i18n/locales/README.md

**Comment by sangyuxiaowu** [comment]
@andercard0  Maybe you read old documents when you started translation work.
Because internationalization has just been introduced, the recent documentation work has been refined, and you can refer to the latest instructions.

antonreshetov has already told you how to modify it, you need to pay attention that the commit comments you submit must meet the requirements, and add a button in the settings interface so that users can choose your language.

Later, I believe that the experience of adding new language support will be optimized, allowing everyone to focus on translation work itself.

Let's help masscode do better together.

**Comment by andercard0** [comment]
> @andercard0 Maybe you read old documents when you started translation work. Because internationalization has just been introduced, the recent documentation work has been refined, and you can refer to the latest instructions.
> 
> antonreshetov has already told you how to modify it, you need to pay attention that the commit comments you submit must meet the requirements, and add a button in the settings interface so that users can choose your language.
> 
> Later, I believe that the experience of adding new language support will be optimized, allowing everyone to focus on translation work itself.
> 
> Let's help masscode do better together.

ah, precisly! my apologies for the confusion tho. I'll look into it later on thanks for the inputs! sorry for any inconvenience

**Comment by antonreshetov** [comment]
@sangyuxiaowu Can you make a PR based on this? It's just that this PR looks abandoned and I plan to just close it.

**Comment by sangyuxiaowu** [comment]
> @sangyuxiaowu Can you make a PR based on this? It's just that this PR looks abandoned and I plan to just close it.

Okay, maybe later, I'm going to the gym.

**Comment by antonreshetov** [comment]
Closed because it was added in #194

**Pull request closed without merging**
